

training:
  epochs: 18
  batch_size: 200

  optimizer:
    obj:SGD : {lr : 0.00001}
    module: torch.optim

  scheduler:
    obj:MultiStepLR : {milestones: [2, 6, 10, 14]}
    module: torch.optim.lr_scheduler

  weight: [0.5, 0.5]
  loss:
    obj:BCELoss : {}
    module: torch.nn


model:
  obj:VGG11 : {}
  module: models

transforms:
  obj:Normalize : {}
  module: dataset.transforms